language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

sudo: false

install: travis_retry composer install --no-interaction --no-scripts --prefer-source

script:
  - ./vendor/bin/phpunit --verbose --coverage-text
